#-x- coding:  utf-8 -x-
#!/usr/bin/env python

# VARIAVEIS DE CONFIGURACAO E INICIALIZACAO
# DOS SISTEMAS ZABBIX, JIRA, TELEGRAM
# ETC...

############################ ZBXJIRA ###################################
CACHE_DIR: /cache
PRODUCAO: True

############################### ZABBIX #################################
zabbix:
 API: True  
 server: xxxxxxxxxxxxxxx
 user: 'xxxxxxxxxxxxxxx'
 passw: 'xxxxxxxxxxxxxxx'
 server_teste: xxxxxxxxxxxxxxx
 user_teste: 'xxxxxxxxxxxxxxx'
 passw_teste: 'xxxxxxxxxxxxxxx'
 loglevel: 0

#################### ATTLASSIAN JIRA E CONFLUENCE ######################
xxxxxxxxxxxxxxx
jira:
 API: True
 server: xxxxxxxxxxxxxxx
 user: xxxxxxx
 passw: xxxxxx
 server_teste: xxxxxxxxxxxxxxx
 user_teste: xxxxxxxxxxxxxxx
 passw_teste: xxxxxxxxxxxxxxx

 servico:  
  monitoramento: 39
 categoria: 
  Evento_de_Alerta: 266

# ID ou value dos elementos de servico de cada
# grupo de responsabilidade
elemento_servico: 
 eventos_anormalidade:  # severidade warning
  DIT-SEGURANCA:   282
  DIT-REDES:   280
  DSA-CAD:   286
  DSA-CNT:   288
  DSJ-HML:   284
  STI-DAU:   290
  STI-MONIT:  291
 eventos_indisponibilidade:  #severidade disaster
  DIT-SEGURANCA:  281
  DIT-REDES:  279
  DSA-CAD:  285
  DSA-CNT:  287
  DSJ-HML:  283
  STI-GOV:  289
  STI-MONIT:  292
 eventos_nao_monitorados:  # severidade ? warning?
  DIT-SEGURANCA:  295
  DIT-REDE:  294
  DSA-CAD:  298
  DSA-CNT:  299
  DSJ-HML:  297
  STI-GOV:  296
  STI-MONIT:  293
eventos_vulnerabilidade:  # severidade ? warning ?
  DIT-SEGURANCA:  302
  DIT-REDES:  301
  DSA-CAD:  305
  DSA-CNT:  306
  DSJ-HML:  304
  STI-GOV:  303
  STI-MONIT:  300
######################################################################## 
campos_form:
 projeto: "'project' : {'id':'13100'}"    #Service Desk (SD)
# tipo: "'issuetype' : {'id':'31'}"        #Incidente
# tab_criador:
#  solicitante: "'reporter' : {'name':'zabbix'}"            
#  departamento:"'customfield_12103' : ['587']"        
#  secretaria: "'customfield_12102' : ['159']"         
#  #cargo: 'customfield_12600' : ['Estagiário'],        
#  email: "'customfield_12213' : ['xxxxxxxxxxxxxxxxxxxxxxxxxxxx']"
#  telefone: "'customfield_11402' : 'xxxx'"                  
# tab_usuario:
#  solicitante:  "'customfield_15907' : {'name':'zabbix'}"
#  departamento: "'customfield_12802' : ['587']"
#  secretaria: 'customfield_12803' : ['159']"  
#  #cargo:"'customfield_12804' : ['Estagiário']",
#  email: "'customfield_12805' : ['xxxxxxxxxxxxxxxxxx']"  
#  telefone: "'customfield_12806' : 'xxxx'" 
# tab_incidente:
#   resumo:"'summary'"      
#   descricao: "'description'"
#   monitoramento: "'customfield_17500':['39']"        # travado na identificacao para Monitoramento id 39
#   evento_alerta: "'customfield_17501':['266']"       # travado na identificação para Evento de alerta id 266
#   elemento_servico: "'customfield_17502':"        # recupera id do elemento em tempo de execucao
#######################################################################

# ID ou value do servico no Jira


confluence:  
 server: xxxxxxxxxxxxxxx
 user: xxxxxxx
 passw: xxxxxxx
 server_teste: xxxxxxxxxxxxxxx
 user_teste: xxxxxxx
 passw_teste: xxxxxxx

########### PROTOCOLADORA DIGITAL DE DOCUMENTOS ELETRONICOS ############
pdde:  
 user: xxxxxxx
 passw: xxxxxxx

############################### TELEGRAM ###############################

# Nome do Bot - MonitoramentoTJ / zbx-tj-bot
# Usuario do Bot - @MonitoramentoTJBot

telegram: 
 token:  xxxxxxxxxxxxxxxxxxx
 destino: 
   monitoramento:  xxxxxxxxxxxxxxx
   grp_alerta_sti:  xxxxxxxxxxxxxxx
   dit-luciano:  xxxxxxxxxxxxxxx
   dit-josuel:  xxxxxxxxxxxxxxx
   dsj:  xxxxxxxxxxxxxxx
   dsa:  xxxxxxxxxxxxxxx

########### ID dos grupos de responsabilidade no Zabbix #################

grupos_responsabilidade: 
 DIT-SEGURANCA:  57
 DIT-REDES:  9
 DSA-CAD:  53
 DSA-CNT:  11
 DSJ-HML:  12
 STI-GOV:  99
 STI-MONIT:  96
 STI-DAU:  122 




